# This rule is not used by the project vault-unseal-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to platform.didactiklabs.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vault-unseal-controller
    app.kubernetes.io/managed-by: kustomize
  name: unseal-viewer-role
rules:
- apiGroups:
  - platform.didactiklabs.io
  resources:
  - unseals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.didactiklabs.io
  resources:
  - unseals/status
  verbs:
  - get
