apiVersion: platform.didactiklabs.io/v1alpha1
kind: Unseal
metadata:
  name: unseal-sample
spec:
  vaultNodes:
    - https://vault-cluster-node-url-1:8200
    - https://vault-cluster-node-url-2:8200
    - https://vault-cluster-node-url-3:8200
  unsealKeysSecretRef:
    name: thresholdkeys
    namespace: vault-unseal-controller-system
  # Optional, but important if you have internal pki for your vault certificate (need to be in the same namespace as the unseal keys secret)
  caCertSecret: cacertificate
  # Optional, set this parameter to true if you want to skip tls certificate verification
  tlsSkipVerify: false
  # Optional
  retryCount: 3
